name       : rocm-cmake
version    : 5.1.3
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocm-cmake/archive/refs/tags/rocm-5.1.3.tar.gz : 19b2da0d56300aab454655b57435ab3ed9e101ecb96561336ea8865bbd993c23
license    : MIT
component  : programming.devel
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm cmake modules
description: |
    ROCm cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
