name       : rocm-cmake
version    : 5.3.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/rocm-cmake/archive/refs/tags/rocm-5.3.3.tar.gz : 3e527f99db52e301ab4f1b994029585951e2ae685f0cdfb7b8529c72f4b77af4
license    : MIT
component  : programming.devel
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm cmake modules
description: |
    ROCm cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
