name       : rocm-cmake
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocm-cmake/archive/refs/tags/rocm-5.0.2.tar.gz : 86a4ae0f84dcf5be95a252295eb732d6a7a271297eed37800a9d492c16474d0c
license    : MIT
component  : programming.devel
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm cmake modules
description: |
    ROCm cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
