name       : rocm-cmake
version    : 5.4.1
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/rocm-cmake/archive/refs/tags/rocm-5.4.1.tar.gz : fdcc97db4c7d418e2b99182947d2e1da2715602eb9f140f6e42c7c056c37aaed
license    : MIT
component  : programming.devel
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm cmake modules
description: |
    ROCm cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
