name       : rocm-hip
version    : 5.1.0
release    : 1
source     :
    - https://github.com/ROCm-Developer-Tools/hipamd/archive/refs/tags/rocm-5.1.0.tar.gz#hipamd.tar.gz : 77984854bfe00f938353fe4c7604d09967eaf5c609d05f1e6423d3c3dea86e61
    - https://github.com/ROCm-Developer-Tools/HIP/archive/refs/tags/rocm-5.1.0.tar.gz#HIP.tar.gz : 47e542183699f4005c48631d96f6a1fbdf27e07ad3402ccd7b5f707c2c602266
license    : MIT
component  : programming.devel
clang      : yes
summary    : AMD ROCm HIP
description: |
    HIP is a C++ Runtime API and Kernel Language that allows developers to create portable applications for AMD and NVIDIA GPUs from single source code.
extract    : False
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libhsakmt)
    - pkgconfig(x11-xcb)
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-rocclr-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
environment: |
    export HIP_CLANG_PATH="/usr/bin"
setup      : |
    tar -xvzf $sources/HIP.tar.gz
    tar -xvzf $sources/hipamd.tar.gz
    cd hipamd-rocm-%version%
    %apply_patches

    #soname is broken when building from tar, upstream is fixing the issue:
    sed -i 's/-${HIP_VERSION_GITHASH}//' CMakeLists.txt

    #HIP requires RPATH
    sed -i "/CMAKE_INSTALL_RPATH/d" CMakeLists.txt

    mkdir build
    cd build
    %cmake -S.. -B. \
        -DHIP_COMMON_DIR=%workdir%/HIP-rocm-%version% \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DHIP_COMPILER=clang \
        -DHIP_VERSION_BUILD_ID=0
build      : |
    cd hipamd-rocm-%version%/build
    %make
install    : |
    cd hipamd-rocm-%version%/build
    %make_install

    #hip installs some cmake modules incorrectly:
    mv %installroot%/usr/cmake %installroot%%libdir%/cmake/Modules

    #make hip-config.cmake less broken, allowing to build stuff that relies on hip
    sed -i 's|${_IMPORT_PREFIX}/../include|${_IMPORT_PREFIX}/include|g' %installroot%%libdir%/cmake/hip/hip-config.cmake
    sed -i 's|"${ROCM_PATH}/llvm"|"/usr"|g' %installroot%%libdir%/cmake/hip/hip-config.cmake
