name       : rocm-hip
version    : 5.1.0
release    : 1
source     :
    - https://github.com/ROCm-Developer-Tools/hipamd/archive/refs/tags/rocm-5.1.0.tar.gz : 77984854bfe00f938353fe4c7604d09967eaf5c609d05f1e6423d3c3dea86e61
    - https://github.com/ROCm-Developer-Tools/HIP/archive/refs/tags/rocm-5.1.0.tar.gz : 47e542183699f4005c48631d96f6a1fbdf27e07ad3402ccd7b5f707c2c602266
license    : MIT
component  : programming.devel
clang      : yes
summary    : AMD ROCm HIP
description: |
    HIP is a C++ Runtime API and Kernel Language that allows developers to create portable applications for AMD and NVIDIA GPUs from single source code.
extract    : False
builddeps  :
    - pkgconfig(OpenCL)
    - pkgconfig(d3d)
    - pkgconfig(gl)
    - pkgconfig(x11-xcb)
    - hsakmt-devel
    - rocm-cmake
    - rocm-compilersupport
    - rocm-device-libs-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
environment: |
    export HIP_CLANG_PATH="/usr/bin"
setup      : |
    tar -xvzf $sources/rocm-5.1.0.tar.gz
    tar -xvzf $sources/rocm-5.1.0.tar.gz.1
    cd hipamd-rocm-%version%
    %apply_patches

    #some hip cmake files don't respect the Linux FHS:
    sed -i "s/\(cmake DESTINATION \)./\1\${LIB_INSTALL_DIR}/" CMakeLists.txt

    #HIP requires RPATH
    sed -i "/CMAKE_INSTALL_RPATH/d" CMakeLists.txt

    mkdir build
    cd build
    %cmake -S.. -B. \
        -DHIP_COMMON_DIR=%workdir%/HIP-rocm-%version% \
        -DHIP_COMPILER=clang \
        -DAMD_OPENCL_INCLUDE_DIR=/usr/include/rocm-opencl/CL \
        -DROCCLR_INCLUDE_DIR=/usr/include/rocclr/include \
        -DCMAKE_MODULE_PATH="/usr/share/cmake/Modules"
build      : |
    cd hipamd-rocm-%version%/build
    %make
install    : |
    cd hipamd-rocm-%version%/build
    %make_install

    #cmake hardcodes libdir, instead of using cmake's gnuinstalldirs
    mv %installroot%%PREFIX%/lib %installroot%%libdir%
    sed -i "s|lib\(/libamdhip64.so\)|lib64\1|" \
        %installroot%%libdir%/cmake/hip*/*.cmake
