name       : hipify
version    : 5.1.3
release    : 1
source     :
    - https://github.com/ROCm-Developer-Tools/HIPIFY/archive/refs/tags/rocm-5.1.3.tar.gz : 6354b08b8ab2f4c481398fb768652bae00bb78c4cec7a11d5f6c7e4cb831ddf1
license    : MIT
component  : programming.tools
summary    : 'HIPify: Convert CUDA to Portable C++ Code (ROCm)'
description: |
    hipify-clang is a clang-based tool for translating CUDA sources into HIP sources. It translates CUDA source into an abstract syntax tree, which is traversed by transformation matchers. After applying all the matchers, the output HIP source is produced.
patterns   : /*
clang      : yes
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_PREFIX=/usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
    rmdir $installdir/usr/bin/lib/linux
    rmdir $installdir/usr/bin/lib
    rmdir $installdir/usr/bin/bin
    rmdir $installdir/usr/bin/share
    rmdir $installdir/usr/bin/include/profile
    mkdir -p $installdir/usr/include/hipify
    mv $installdir/usr/bin/include/* $installdir/usr/include/hipify
    rmdir $installdir/usr/bin/include
