name       : hsakmt
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/rocm-5.1.0.tar.gz : 032717e80b1aefed59f11399e575564ee86ee7c125e889f7c79c2afdfab1eb93
license    : NCSA
component  : xorg.driver
clang      : yes
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libpci)
    - numactl-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
