name       : hsakmt
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/rocm-5.0.2.tar.gz : f2a27ac18aada1dc0dba6455beb7dd7d88a4457c1917024ea372fecb03356e97
license    : NCSA
component  : xorg.driver
clang      : yes
summary    : libhsakmt (HSA thunk) libraries for AMD KFD
description: |
    libhsakmt (HSA thunk) libraries for AMD KFD
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libpci)
    - pkgconfig(numa)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
