name       : hsakmt
version    : 5.3.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/archive/rocm-5.3.3.tar.gz : b5350de915997ed48072b37a21c2c44438028255f6cc147c25a196ad383c52e7
license    : NCSA
component  : xorg.driver
clang      : yes
summary    : libhsakmt (HSA thunk) libraries for AMD KFD
description: |
    libhsakmt (HSA thunk) libraries for AMD KFD
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libpci)
    - pkgconfig(numa)
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
