name       : rocm-device-libs
version    : 5.4.1
release    : 2
source     :
    - https://github.com/Mystro256/ROCm-Device-Libs/archive/refs/tags/15.1.tar.gz : 52bda0ab3e6818969f9455482f8a328d1be32f0682b23c244926d7bde924f4e0
license    : NCSA
component  : xorg.driver
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Device Libraries
description: |
    This package contains a set of AMD specific device-side language runtime libraries in the form of bit code. Specifically:
    - Open Compute library controls
    - Open Compute Math library
    - Open Compute Kernel library
    - OpenCL built-in library
    - HIP built-in library
    - Heterogeneous Compute built-in library
builddeps  :
    - rocm-cmake
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-FHS-compliant-install.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
