name       : rocm-device-libs
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/refs/tags/rocm-5.1.0.tar.gz : 47dbcb41fb4739219cadc9f2b5f21358ed2f9895ce786d2f7a1b2c4fd044d30f
license    : NCSA
component  : xorg.driver
clang      : yes
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-FHS-compliant-install.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
