name       : rocm-device-libs
version    : 5.1.3
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/refs/tags/rocm-5.1.3.tar.gz : c41958560ec29c8bf91332b9f668793463904a2081c330c0d828bf2f91d4f04e
license    : NCSA
component  : xorg.driver
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Device Libraries
description: |
    This package contains a set of AMD specific device-side language runtime libraries in the form of bit code. Specifically:
    - Open Compute library controls
    - Open Compute Math library
    - Open Compute Kernel library
    - OpenCL built-in library
    - HIP built-in library
    - Heterogeneous Compute built-in library
builddeps  :
    - rocm-cmake
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-FHS-compliant-install.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
