name       : rocm-device-libs
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/refs/tags/rocm-5.0.2.tar.gz : 49cfa8f8fc276ba27feef40546788a2aabe259a924a97af8bef24e295d19aa5e
license    : NCSA
component  : xorg.driver
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Device Libraries
description: |
    This package contains a set of AMD specific device-side language runtime libraries in the form of bit code. Specifically:
    - Open Compute library controls
    - Open Compute Math library
    - Open Compute Kernel library
    - OpenCL built-in library
    - HIP built-in library
    - Heterogeneous Compute built-in library
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-FHS-compliant-install.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
