name       : rocm-device-libs
version    : 5.3.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/refs/tags/rocm-5.3.3.tar.gz : 963c9a0561111788b55a8c3b492e2a5737047914752376226c97a28122a4d768
license    : NCSA
component  : xorg.driver
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Device Libraries
description: |
    This package contains a set of AMD specific device-side language runtime libraries in the form of bit code. Specifically:
    - Open Compute library controls
    - Open Compute Math library
    - Open Compute Kernel library
    - OpenCL built-in library
    - HIP built-in library
    - Heterogeneous Compute built-in library
builddeps  :
    - rocm-cmake
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-FHS-compliant-install.patch
    %patch -p1 < $pkgfiles/0001-fix-atomic.fadd.f32.p1.f32.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # mv $installdir/usr/amdgcn $installdir/%libdir%/
check      : |
    if [ -d /dev/kfd ]; then
        %ninja_check
    fi
