name       : rocminfo
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/refs/tags/rocm-5.1.0.tar.gz : 76f6cc9e69d9fc7e692e5c7db35e89079d3b1d2d47632e4742d612e743c396d3
homepage   : https://github.com/RadeonOpenCompute/rocminfo/
license    : NCSA
component  : programming.devel
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - rocm-runtime-devel
setup      : |
    %apply_patches
    %cmake_ninja -DROCM_DIR="/usr"
build      : |
    %ninja_build
install    : |
    %ninja_install
