name       : rocminfo
version    : 5.1.3
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/refs/tags/rocm-5.1.3.tar.gz : 7aecd7b189e129b77c8f2af70be2926a0f3a5ee89814879bc8477924a7e6f2ae
homepage   : https://github.com/RadeonOpenCompute/rocminfo/
license    : NCSA
component  : programming.devel
clang      : yes
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - rocm-cmake
    - rocm-runtime-devel
setup      : |
    %apply_patches
    %cmake_ninja -DROCM_DIR=%PREFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
