name       : rocminfo
version    : 5.3.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/refs/tags/rocm-5.3.3.tar.gz : 77e6adc81da6c1d153517e1d28db774205531a2ec188e6518f998328ef7897c6
homepage   : https://github.com/RadeonOpenCompute/rocminfo/
license    : NCSA
component  : programming.devel
clang      : yes
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - rocm-cmake
    - rocm-runtime-devel
setup      : |
    %cmake_ninja -DROCRTST_BLD_TYPE="Release"
build      : |
    %ninja_build
install    : |
    %ninja_install
