name       : rocminfo
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/refs/tags/rocm-5.0.0.tar.gz : 43e025de31bffa335d9cb682649add886afdd02c92090ee63e9bf77b3aaaa75b
homepage   : https://github.com/RadeonOpenCompute/rocminfo/
license    : NCSA
component  : programming.devel
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - rocm-runtime-devel
setup      : |
    %apply_patches
    %cmake_ninja -DROCM_DIR=%PREFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
