name       : python-cppheaderparser
version    : 2.7.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/3c/ba/d8d168a4b54cae66eaf13d1d9197ca9349c94653815e061f79e7eed86c01/CppHeaderParser-2.7.4.tar.gz : 382b30416d95b0a5e8502b214810dcac2a56432917e2651447d3abe253e3cc42
license    : BSD-3
component  : programming.python
summary    : Parse C++ header files and generate a data structure representing the class
description: |
    Parse C++ header files and generate a data structure representing the class
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-ply
build      : |
    %python3_setup
install    : |
    %python3_install
