name       : numactl
version    : 2.0.14
release    : 2
source     :
    - https://github.com/numactl/numactl/archive/v2.0.14.tar.gz : 1ee27abd07ff6ba140aaf9bc6379b37825e54496e01d6f7343330cf1a4487035
homepage   : https://github.com/numactl/numactl
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : programming.devel
summary    : Simple NUMA policy support for Linux.
description: |
    Simple NUMA policy support. It consists of a numactl program to run other programs with a specific NUMA policy and a libnuma shared library ("NUMA API") to set NUMA policy in applications.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
