name       : rocm-compilersupport
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/refs/tags/rocm-5.0.0.tar.gz : da1bbc694bd930a504406eb0a0018c2e317d8b2c136fb2cab8de426870efe9a8
license    : NCSA
component  : programming.devel
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : The AMD Code Object Manager (Comgr)
description: |
    The AMD Code Object Manager (Comgr) is a shared library which provides operations for creating and inspecting code objects.
builddeps  :
    - rocm-device-libs-devel
setup      : |
    %apply_patches
    sed -i -e "/compile_test/d" \
    -e "/compile_minimal_test/d" \
    -e "/compile_device_libs_test/d" \
    -e "/compile_source_with_device_libs_to_bc_test/d" \
    lib/comgr/test/CMakeLists.txt
    %cmake -S lib/comgr
build      : |
    %make
install    : |
    %make_install
