name       : rocm-compilersupport
version    : 5.3.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/refs/tags/rocm-5.3.3.tar.gz : 6a4ef69e672a077b5909977248445f0eedf5e124af9812993a4d444be030c78b
license    : NCSA
component  : programming.devel
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : The AMD Code Object Manager (Comgr)
description: |
    The AMD Code Object Manager (Comgr) is a shared library which provides operations for creating and inspecting code objects.
builddeps  :
    - rocm-cmake
    - rocm-device-libs-devel
setup      : |
    %apply_patches

    ##Fix issue wit HIP, where compilation flags are incorrect, see issue:
    #https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/issues/49
    #Remove redundant includes:
    sed -i '/Args.push_back(HIPIncludePath/,+1d' lib/comgr/src/comgr-compiler.cpp
    sed -i '/Args.push_back(ROCMIncludePath/,+1d' lib/comgr/src/comgr-compiler.cpp
    #Source hard codes the libdir too:
    sed -i 's/lib\(\/clang\)/%{_lib}\1/' lib/comgr/src/comgr-compiler.cpp

    %cmake -S lib/comgr -DBUILD_TESTING=ON \
                        -DFILE_REORG_BACKWARD_COMPATIBILITY=OFF
build      : |
    %make
install    : |
    %make_install

    #remove textfiles that are not useful for the users
    rm -r %installroot%/usr/share
check      : |
    if [ -d /dev/kfd ]; then
        make test
    fi
