name       : rocm-compilersupport
version    : 5.1.3
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/refs/tags/rocm-5.1.3.tar.gz : 3078c10e9a852fe8357712a263ad775b15944e083f93a879935c877511066ac9
license    : NCSA
component  : programming.devel
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : The AMD Code Object Manager (Comgr)
description: |
    The AMD Code Object Manager (Comgr) is a shared library which provides operations for creating and inspecting code objects.
builddeps  :
    - rocm-cmake
    - rocm-device-libs-devel
setup      : |
    %apply_patches
    sed -i -e "/compile_test/d" \
    -e "/compile_minimal_test/d" \
    -e "/compile_device_libs_test/d" \
    -e "/compile_source_with_device_libs_to_bc_test/d" \
    lib/comgr/test/CMakeLists.txt
    %cmake -S lib/comgr
build      : |
    %make
install    : |
    %make_install

    #remove textfiles that are not useful for the users
    rm -r %installroot%/usr/share
