name       : rocprim
version    : 2.10.13
release    : 1
source     :
    - https://github.com/ROCmSoftwarePlatform/rocPRIM/archive/refs/tags/rocm-5.1.3.tar.gz : b5a08d2e76388bd1ffa6c946009928fe95de846ab6b65a6475998070c0cf6dc1
license    : MIT
component  : programming.library
summary    : ROCm Parallel Primitives
description: |
    rocPRIM is a header-only library providing HIP parallel primitives for developing performant GPU-accelerated code on AMD ROCm platform.
clang      : yes
builddeps  :
    - rocminfo
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-hip-devel
    - rocm-opencl-devel
    - rocm-runtime-devel
    - rocm-smi-devel
    - git
environment: |
    export CCACHE_MAXSIZE=100G
    export ROCM_PATH=%PREFIX%
    export ROCM_DIR=%PREFIX%
    export HIP_PLATFORM=amd
    export HIP_RUNTIME=rocclr
    export DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_DEVICE_LIB_PATH=/usr/lib64/amdgcn/bitcode
    export HIP_COMPILER=clang
    export HIP_CLANG_PATH=/usr/bin
    export HSA_PATH=/usr/hsa
    export LLVM_PATH=/usr
    # https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-5.1.x/docs/markdown/clang_options.md
    # export CFLAGS="-fcf-protection=none"
    # export CXXFLAGS="-fcf-protection=none"
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
