name       : rocm-opencl
version    : 5.3.3
release    : 2
source     :
    - https://github.com/ROCm-Developer-Tools/ROCclr/archive/refs/tags/rocm-5.3.3.tar.gz#ROCclr-5.3.3.tar.gz : f8133a5934f9c53b253d324876d74f08a19e2f5b073bc94a62fe64b0d2183a18
    - https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/archive/refs/tags/rocm-5.3.3.tar.gz#ROCm-OpenCL-Runtime-5.3.3.tar.gz : cab394e6ef16c35bab8de29a66b96a7dc0e7d1297aaacba3718fa1d369233c9f
license    : MIT
component  : programming.devel
clang      : yes
summary    :
    - OpenCL 2.2 compatible language runtime for AMD Radeon GPUs
    - rocm-rocclr : Radeon Open Compute Common Language Runtime
    - rocm-rocclr-devel : ROCclr development package
description: |
    OpenCL 2.2 compatible language runtime for AMD Radeon GPUs
extract    : False
rundeps    :
    - rocminfo
    - rocm-compilersupport
builddeps  :
    - pkgconfig(OpenCL)
    - pkgconfig(d3d)
    - pkgconfig(gl)
    - pkgconfig(libhsakmt)
    - pkgconfig(numa)
    - pkgconfig(x11-xcb)
    - rocm-cmake
    - rocm-compilersupport-devel
    - rocm-device-libs-devel
    - rocm-runtime-devel
environment: |
    export CXXFLAGS="$CXXFLAGS -I/usr/include/amd_comgr/"
setup      : |
    tar -xvzf $sources/ROCclr-%version%.tar.gz
    tar -xvzf $sources/ROCm-OpenCL-Runtime-%version%.tar.gz --strip-components=1

    pushd ROCclr-rocm-%version%
    %patch -p1 < $pkgfiles/0001-enable-gfx800.patch
    popd

    %cmake_ninja -Wno-dev  \
        -DAMD_OPENCL_PATH="%workdir%" \
        -DROCM_PATH=%PREFIX% \
        -DROCCLR_PATH="%workdir%/ROCclr-rocm-%version%" \
        -DBUILD_ICD=OFF \
        -DROCM_DIR=%PREFIX% \
        -DFILE_REORG_BACKWARD_COMPATIBILITY=OFF \
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00644 config/amdocl64.icd $installdir/usr/share/OpenCL/vendors/amdocl64.icd

    # Avoid file conflicts with opencl-headers package:
    mkdir -p $installdir/usr/include/rocm-opencl
    mv $installdir/usr/include/CL $installdir/usr/include/rocm-opencl/CL

    #Avoid file conflicts with clinfo package:
    mv $installdir/usr/bin/clinfo $installdir/usr/bin/rocm-clinfo
