name       : rocm-opencl
version    : 5.0.0
release    : 1
source     :
    - https://github.com/ROCm-Developer-Tools/ROCclr/archive/refs/tags/rocm-5.0.0.tar.gz : 6b72faf8819628a5c109b2ade515ab9009606d10f11316f0d7e4c4c998d7f724
    - https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/archive/refs/tags/rocm-5.0.0.tar.gz : 2aa3a628b336461f83866c4e76225ef5338359e31f802987699d6308515ae1be
license    : MIT
component  : programming.devel
clang      : yes
summary    : OpenCL 2.2 compatible language runtime
description: |
    OpenCL 2.2 compatible language runtime
extract    : False
builddeps  :
    - pkgconfig(OpenCL)
    - pkgconfig(d3d)
    - pkgconfig(gl)
    - pkgconfig(x11-xcb)
    - hsakmt-devel
    - rocm-cmake
    - rocm-compilersupport
    - rocm-device-libs-devel
    - rocm-runtime-devel
setup      : |
    tar -xvzf $sources/rocm-5.0.0.tar.gz
    tar -xvzf $sources/rocm-5.0.0.tar.gz.1
    pushd ROCclr-rocm-%version%
    %patch -p1 < $pkgfiles/0001-enable-gfx800.patch
    %patch -p1 < $pkgfiles/0001-Allow-ROCclr-to-be-built-standalone.patch
    sed -i "s/STATIC/SHARED/" cmake/ROCclr.cmake
    echo "set_target_properties(rocclr PROPERTIES VERSION 5.0.0 SOVERSION 5.0)" \
    >> cmake/ROCclr.cmake
    %cmake -Wno-dev \
        -DAMD_OPENCL_PATH="%workdir%/ROCm-OpenCL-Runtime-rocm-%version%"
    popd
    pushd ROCm-OpenCL-Runtime-rocm-%version%
    #ls -d khronos/icd/* | grep -v loader | xargs rm -r
    #ls -d khronos/icd/loader/* | grep -v icd_dispatch.h | xargs rm -r
    ls -d khronos/headers/* | grep -v opencl2.2 | xargs rm -r
    rm -r khronos/headers/*/tests/
    sed -i -e "/add_subdirectory(khronos\/icd)/d" \
     -e "/get_target_property(OPENCL_LIB_/d" CMakeLists.txt
    #apply_patches
    %cmake -Wno-dev  \
        -DCMAKE_MODULE_PATH="%workdir%/ROCclr-rocm-%version%" \
        -DROCM_PATH=%PREFIX% \
        -DROCCLR_PATH="%workdir%/ROCclr-rocm-%version%" \
        -DAMD_OPENCL_PATH="%workdir%/ROCm-OpenCL-Runtime-rocm-%version%" -DBUILD_ICD=OFF
build      : |
    pushd ROCclr-rocm-%version%
    %make
    popd
    pushd ROCm-OpenCL-Runtime-rocm-%version%
    %make
install    : |
    pushd ROCclr-rocm-%version%
    %make_install

    popd
    pushd ROCm-OpenCL-Runtime-rocm-%version%
    %make_install

    install -Dm00644 config/amdocl64.icd \
    %installroot%/usr/share/OpenCL/vendors/amdocl64.icd

    #Avoid file conflicts with opencl-headers package:
    mkdir -p %installroot%/usr/include/rocm-opencl
    mv %installroot%/usr/include/CL %installroot%/usr/include/rocm-opencl/CL

    #CMake excludes installing this for some reason
    install -Dm00644 khronos/headers/opencl2.2/CL/cl_egl.h \
        %installroot%/usr/include/rocm-opencl/CL

    #Install bundled khronos icd header that hip needs:
    install -Dm00644 khronos/icd/loader/icd_dispatch.h \
        %installroot%/usr/include/rocm-opencl/icd/loader/icd_dispatch.h

    #Avoid file conflicts with clinfo package:
    mv %installroot%/usr/bin/clinfo %installroot%/usr/bin/rocm-clinfo
