name       : rocm-runtime
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCR-Runtime/archive/refs/tags/rocm-5.0.0.tar.gz : 61644365ea2b09fa7ec22f3dbdb74f2b6b1daa34b180138da9e0c856006a373e
license    : NCSA
component  : programming.devel
clang      : yes
homepage   : https://github.com/RadeonOpenCompute
summary    : ROCm Runtime Library
description: |
    The ROCm Runtime Library is a thin, user-mode API that exposes the necessary interfaces to access and interact with graphics hardware driven by the AMDGPU driver set and the AMDKFD kernel driver. Together they enable programmers to directly harness the power of AMD discrete graphics devices by allowing host applications to launch compute kernels directly to the graphics hardware.
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(libelf)
    - hsakmt-devel
    - pkgconfig(numa)
    - rocm-device-libs-devel
    - vim
setup      : |
    ls -ltra
    %apply_patches
    %cmake -S src -DBITCODE_DIR="%libdir%/amdgcn/bitcode"
build      : |
    %make
install    : |
    %make_install
