name       : rocm-smi
version    : 5.1.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocm_smi_lib/archive/refs/tags/rocm-5.1.0.tar.gz : 21b31b43015b77a9119cf4c1d4ff3864f9ef1f34e2a52a38f985a3f710dc5f87
license    : NCSA
component  : programming.devel
summary    : ROCm System Management Interface Library
description: |
    ROCm System Management Interface Library
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
