name       : rocm-smi
version    : 5.3.3
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/rocm_smi_lib/archive/refs/tags/rocm-5.3.3.tar.gz : c2c2a377c2e84f0c40297a97b6060dddc49183c2771b833ebe91ed98a98e4119
license    : NCSA
component  : programming.devel
summary    : ROCm System Management Interface Library
description: |
    ROCm System Management Interface Library
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-missing-string-header-for-memcpy.patch
    %cmake_ninja -DFILE_REORG_BACKWARD_COMPATIBILITY=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
