name       : rocm-smi
version    : 5.1.3
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocm_smi_lib/archive/refs/tags/rocm-5.1.3.tar.gz : 8a19ce60dc9221545aa50e83e88d8c4be9bf7cde2425cefb13710131dc1d7b1b
license    : NCSA
component  : programming.devel
summary    : ROCm System Management Interface Library
description: |
    ROCm System Management Interface Library
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
